{
    'name': 'Helpdesk SLA',
    'version': '16.0.0.1',
    'summary': 'Add ticket priority field to helpdesk tickets and manage SLAs',
    'description': 'This module adds a priority field to helpdesk tickets and provides a way to manage SLAs.',
    'author': 'The Open Source Company',
    'category': 'Helpdesk',
    'depends': ['helpdesk_mgmt'],
    'data': [
        'security/ir.model.access.csv',
        'views/helpdesk_ticket_views.xml',
        'views/helpdesk_sla_views.xml',
        'views/sla_line_views.xml',
        'data/ir_cron_data.xml',
        'data/data.xml',
        'views/menuitem.xml',
    ],
    'installable': True,
    'application': False,
}
